### PR TITLE
Add MonadCatch and MonadMask instances to LevelDBT

### PR DESCRIPTION
**Pull request by eryx67**
Just added instances to support exceptions handling inside LevelDBT.

### CODE REVIEW

**Comment by jeremyjh** [comment]
I'm not a super big fan of adding dependencies just to support instances, though I understand the dilemma. Two alternatives I can offer: one make it optional with cabal flags and CPP, two make a separate package higher-levedb-exceptions for the instances and I'll endorse it in the readme so they are the "canonical" orphans.

**Comment by eryx67** [comment]
Both variants are suitable. But if you choose second can you change package name to
something like higher-levedb-instances? Somebody would like to add other instances
supported by ResourceT.

**Comment by jeremyjh** [comment]
Sorry, I had missed that `exceptions` is already a transitive dependency - its a dependency of `resourcet`. So I can take this as is, thanks!

**Comment by jeremyjh** [comment]
New version 0.4.0.0 is on Hackage.

**Pull request merged**
